# Generated by Django 3.0.7 on 2020-06-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category',
            name='source_type',
            field=models.CharField(choices=[('UPLOAD', 'UPLOAD'), ('YOUTUBE', 'YOUTUBE'), ('URL', 'URL')], default='URL', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='source_type',
            field=models.CharField(choices=[('UPLOAD', 'UPLOAD'), ('YOUTUBE', 'YOUTUBE'), ('URL', 'URL')], max_length=10),
        ),
    ]
