# Generated by Django 3.0.7 on 2020-06-12 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0002_auto_20200612_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='source_type',
            new_name='icon_source',
        ),
    ]
